version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app  # Mounts the local backend code
    environment:
      - ENVIRONMENT=development
      - RELOAD=True  # Enable auto-reload for FastAPI
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app/frontend
    command: streamlit run /app/frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0

